services:
  bot:
    build: .
    environment:
      DATABASE_URL: "postgres://lemonmail:${POSTGRES_PASSWORD}@db/lemonmail"
      DISCORD_BOT_TOKEN: "${DISCORD_BOT_TOKEN}"
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: "lemonmail"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - lemonmail-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  lemonmail-data:
